// ---------------------------------------------------------------------------
// EduOS — StudentIDCard
//
// A printable student ID card rendered inside a modal dialog.
//
// Card layout (top → bottom):
//   ┌──────────────────────────────────────────┐
//   │  [Institute Logo]   EduOS Platform        │
//   │  ──────────────────────────────────────── │
//   │  [Avatar initials]                        │
//   │  STUDENT NAME                             │
//   │  Admission No: 2024-001                   │
//   │  ──────────────────────────────────────── │
//   │  Status: Active     Joined: 15 Jan 2025   │
//   │  Phone: +91 98765 43210                   │
//   │  ──────────────────────────────────────── │
//   │  [QR Code]     Emergency Contact:         │
//   │                Name: …                    │
//   │                Phone: …                   │
//   └──────────────────────────────────────────┘
//
// The modal provides a "Print ID Card" button (window.print()) and a "Close"
// button.  Print-specific styles hide the modal chrome and reveal only the
// card surface using Tailwind `print:` variants.
// ---------------------------------------------------------------------------

import { useEffect } from "react";
import { X, Printer } from "lucide-react";

import type { Student } from "@/types";
import { getInitials, formatDate } from "@/utils/helpers";
import { StatusBadge } from "@/components/ui/StatusBadge";

// ── Props ─────────────────────────────────────────────────────────────────────

interface StudentIDCardProps {
  student: Student;
  instituteName: string;
  instituteLogo?: string;
  isOpen: boolean;
  onClose: () => void;
}

// ── Sub-components ────────────────────────────────────────────────────────────

/** Thin divider line used between card sections. */
function CardDivider() {
  return <div className="my-3 border-t border-gray-200" aria-hidden="true" />;
}

// ── Component ─────────────────────────────────────────────────────────────────

/**
 * `StudentIDCard` — printable ID card in a modal wrapper.
 *
 * The card itself uses only static Tailwind classes (no dark-mode variants)
 * so it prints consistently regardless of the user's OS colour scheme.
 *
 * The QR code is generated by the free `api.qrserver.com` service — no npm
 * package needed.  It encodes `STUDENT:<id>:<admission_no>` for scanning.
 */
export function StudentIDCard({
  student,
  instituteName,
  instituteLogo,
  isOpen,
  onClose,
}: StudentIDCardProps) {
  // Close on Escape key
  useEffect(() => {
    if (!isOpen) return;
    function handleKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const ec = student.emergency_contact;
  const qrData = encodeURIComponent(`STUDENT:${student.id}:${student.admission_no}`);

  return (
    <>
      {/* ── Backdrop ────────────────────────────────────────────────────────── */}
      <div
        aria-hidden="true"
        onClick={onClose}
        className="fixed inset-0 z-50 bg-black/50 print:hidden"
      />

      {/* ── Modal shell ─────────────────────────────────────────────────────── */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Student ID Card"
        className="fixed left-1/2 top-1/2 z-50 w-full max-w-sm -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-card border border-border shadow-2xl print:static print:translate-x-0 print:translate-y-0 print:rounded-none print:shadow-none print:border-0"
      >
        {/* ── Modal header (hidden on print) ─────────────────────────────── */}
        <div className="flex items-center justify-between border-b border-border px-5 py-3 print:hidden">
          <p className="text-sm font-semibold text-foreground">Student ID Card</p>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          >
            <X className="h-4 w-4" aria-hidden="true" />
          </button>
        </div>

        {/* ── ID Card surface ─────────────────────────────────────────────── */}
        {/*
          All classes here use static colours (no dark: variants) so the
          printed card is always white-on-dark-text regardless of OS mode.
        */}
        <div id="student-id-card" className="overflow-hidden rounded-b-2xl print:rounded-none">
          {/* Header stripe */}
          <div className="bg-primary px-5 py-4 flex items-center gap-3">
            {/* Institute logo or initials placeholder */}
            {instituteLogo ? (
              <img
                src={instituteLogo}
                alt={instituteName}
                className="h-10 w-10 rounded-full object-cover bg-white"
              />
            ) : (
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-white/20 text-white text-xs font-bold select-none">
                {getInitials(instituteName)}
              </div>
            )}
            <div className="min-w-0">
              <p className="text-xs font-medium text-primary-foreground/80 leading-tight">
                EduOS Platform
              </p>
              <p className="text-sm font-bold text-primary-foreground leading-tight truncate">
                {instituteName}
              </p>
            </div>
          </div>

          {/* Card body */}
          <div className="bg-white px-5 py-5">
            {/* Avatar + name */}
            <div className="flex flex-col items-center gap-2 text-center">
              <div
                className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-xl font-bold text-primary-foreground select-none"
                aria-hidden="true"
              >
                {getInitials(student.user?.name ?? "?")}
              </div>
              <div>
                <p className="text-base font-bold text-gray-900 uppercase tracking-wide">
                  {student.user?.name ?? "Not Added"}
                </p>
                <p className="font-mono text-xs text-gray-500 mt-0.5">
                  Admission No: {student.admission_no}
                </p>
              </div>
            </div>

            <CardDivider />

            {/* Status + Joined */}
            <div className="flex items-center justify-between gap-2 text-xs text-gray-600">
              <div className="flex items-center gap-1.5">
                <span className="font-medium text-gray-700">Status:</span>
                <StatusBadge status={student.status} size="sm" />
              </div>
              <div>
                <span className="font-medium text-gray-700">Joined: </span>
                {formatDate(student.created_at)}
              </div>
            </div>

            {/* Phone */}
            {student.user?.phone && (
              <p className="mt-2 text-xs text-gray-600">
                <span className="font-medium text-gray-700">Phone: </span>
                {student.user.phone}
              </p>
            )}

            {!student.user?.phone && (
              <p className="mt-2 text-xs text-gray-600">
                <span className="font-medium text-gray-700">Phone: </span>
                Not Added
              </p>
            )}

            <CardDivider />

            {/* QR + Emergency contact */}
            <div className="flex items-start justify-between gap-4">
              {/* QR code */}
              <div className="shrink-0">
                <img
                  src={`https://api.qrserver.com/v1/create-qr-code/?size=80x80&data=${qrData}`}
                  alt="Student QR"
                  className="h-20 w-20 rounded-md border border-gray-200"
                />
              </div>

              {/* Emergency contact */}
              {ec && (ec.name || ec.phone) ? (
                <div className="min-w-0 flex-1">
                  <p className="text-xs font-semibold text-gray-700 mb-1">Emergency Contact</p>
                  {ec.name && (
                    <p className="text-xs text-gray-600">
                      <span className="font-medium">Name: </span>
                      {ec.name}
                    </p>
                  )}
                  {ec.relation && (
                    <p className="text-xs text-gray-600 capitalize">
                      <span className="font-medium">Relation: </span>
                      {ec.relation}
                    </p>
                  )}
                  {ec.phone && (
                    <p className="text-xs text-gray-600">
                      <span className="font-medium">Phone: </span>
                      {ec.phone}
                    </p>
                  )}
                  {!ec.name && !ec.relation && !ec.phone && (
                    <p className="text-xs text-gray-600">Not Added</p>
                  )}
                </div>
              ) : (
                <div className="min-w-0 flex-1">
                  <p className="text-xs text-gray-400 italic">No emergency contact on file.</p>
                </div>
              )}
            </div>

            {/* Footer note */}
            <p className="mt-4 text-center text-[10px] text-gray-400">
              This card is the property of {instituteName}. If found, please return it.
            </p>
          </div>
        </div>

        {/* ── Action buttons (hidden on print) ────────────────────────────── */}
        <div className="flex items-center justify-end gap-2 border-t border-border px-5 py-3 print:hidden">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-border bg-background px-3 py-2 text-sm font-medium text-foreground transition-colors hover:bg-muted"
          >
            Close
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            <Printer className="h-4 w-4" aria-hidden="true" />
            Print ID Card
          </button>
        </div>
      </div>
    </>
  );
}
