/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthRegisterInstituteRouteImport } from './routes/auth/register-institute'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSuperAdminIndexRouteImport } from './routes/dashboard/super-admin/index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardParentIndexRouteImport } from './routes/dashboard/parent/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardStudentStudyLogsRouteImport } from './routes/dashboard/student/study-logs'
import { Route as DashboardStudentMyLearningRouteImport } from './routes/dashboard/student/my-learning'
import { Route as DashboardStudentExamsIndexRouteImport } from './routes/dashboard/student/exams/index'
import { Route as DashboardStudentCoursesIndexRouteImport } from './routes/dashboard/student/courses/index'
import { Route as DashboardStudentAssignmentsIndexRouteImport } from './routes/dashboard/student/assignments/index'
import { Route as DashboardStaffStudentsIndexRouteImport } from './routes/dashboard/staff/students/index'
import { Route as DashboardStaffCoursesIndexRouteImport } from './routes/dashboard/staff/courses/index'
import { Route as DashboardAdminStudyLogsIndexRouteImport } from './routes/dashboard/admin/study-logs/index'
import { Route as DashboardAdminStudentsIndexRouteImport } from './routes/dashboard/admin/students/index'
import { Route as DashboardAdminStaffIndexRouteImport } from './routes/dashboard/admin/staff/index'
import { Route as DashboardAdminScheduleIndexRouteImport } from './routes/dashboard/admin/schedule/index'
import { Route as DashboardAdminParentsIndexRouteImport } from './routes/dashboard/admin/parents/index'
import { Route as DashboardAdminFeesIndexRouteImport } from './routes/dashboard/admin/fees/index'
import { Route as DashboardAdminExamsIndexRouteImport } from './routes/dashboard/admin/exams/index'
import { Route as DashboardAdminCoursesIndexRouteImport } from './routes/dashboard/admin/courses/index'
import { Route as DashboardAdminBatchesIndexRouteImport } from './routes/dashboard/admin/batches/index'
import { Route as DashboardAdminAttendanceIndexRouteImport } from './routes/dashboard/admin/attendance/index'
import { Route as DashboardAdminAssignmentsIndexRouteImport } from './routes/dashboard/admin/assignments/index'
import { Route as DashboardStudentLearnCourseIdRouteImport } from './routes/dashboard/student/learn/$courseId'
import { Route as DashboardStaffStudentsStudentIdRouteImport } from './routes/dashboard/staff/students/$studentId'
import { Route as DashboardAdminStudentsStudentIdRouteImport } from './routes/dashboard/admin/students/$studentId'
import { Route as DashboardAdminExamsCreateRouteImport } from './routes/dashboard/admin/exams/create'
import { Route as DashboardAdminExamsExamIdRouteImport } from './routes/dashboard/admin/exams/$examId'
import { Route as DashboardAdminCoursesCreateRouteImport } from './routes/dashboard/admin/courses/create'
import { Route as DashboardAdminCoursesCourseIdRouteImport } from './routes/dashboard/admin/courses/$courseId'
import { Route as DashboardStudentExamsExamIdAttemptRouteImport } from './routes/dashboard/student/exams/$examId.attempt'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterInstituteRoute = AuthRegisterInstituteRouteImport.update({
  id: '/auth/register-institute',
  path: '/auth/register-institute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuperAdminIndexRoute =
  DashboardSuperAdminIndexRouteImport.update({
    id: '/super-admin/',
    path: '/super-admin/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentIndexRoute = DashboardParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentStudyLogsRoute =
  DashboardStudentStudyLogsRouteImport.update({
    id: '/student/study-logs',
    path: '/student/study-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentMyLearningRoute =
  DashboardStudentMyLearningRouteImport.update({
    id: '/student/my-learning',
    path: '/student/my-learning',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentExamsIndexRoute =
  DashboardStudentExamsIndexRouteImport.update({
    id: '/student/exams/',
    path: '/student/exams/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentCoursesIndexRoute =
  DashboardStudentCoursesIndexRouteImport.update({
    id: '/student/courses/',
    path: '/student/courses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentAssignmentsIndexRoute =
  DashboardStudentAssignmentsIndexRouteImport.update({
    id: '/student/assignments/',
    path: '/student/assignments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffStudentsIndexRoute =
  DashboardStaffStudentsIndexRouteImport.update({
    id: '/staff/students/',
    path: '/staff/students/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffCoursesIndexRoute =
  DashboardStaffCoursesIndexRouteImport.update({
    id: '/staff/courses/',
    path: '/staff/courses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudyLogsIndexRoute =
  DashboardAdminStudyLogsIndexRouteImport.update({
    id: '/admin/study-logs/',
    path: '/admin/study-logs/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudentsIndexRoute =
  DashboardAdminStudentsIndexRouteImport.update({
    id: '/admin/students/',
    path: '/admin/students/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStaffIndexRoute =
  DashboardAdminStaffIndexRouteImport.update({
    id: '/admin/staff/',
    path: '/admin/staff/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminScheduleIndexRoute =
  DashboardAdminScheduleIndexRouteImport.update({
    id: '/admin/schedule/',
    path: '/admin/schedule/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminParentsIndexRoute =
  DashboardAdminParentsIndexRouteImport.update({
    id: '/admin/parents/',
    path: '/admin/parents/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminFeesIndexRoute = DashboardAdminFeesIndexRouteImport.update({
  id: '/admin/fees/',
  path: '/admin/fees/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminExamsIndexRoute =
  DashboardAdminExamsIndexRouteImport.update({
    id: '/admin/exams/',
    path: '/admin/exams/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCoursesIndexRoute =
  DashboardAdminCoursesIndexRouteImport.update({
    id: '/admin/courses/',
    path: '/admin/courses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminBatchesIndexRoute =
  DashboardAdminBatchesIndexRouteImport.update({
    id: '/admin/batches/',
    path: '/admin/batches/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAttendanceIndexRoute =
  DashboardAdminAttendanceIndexRouteImport.update({
    id: '/admin/attendance/',
    path: '/admin/attendance/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAssignmentsIndexRoute =
  DashboardAdminAssignmentsIndexRouteImport.update({
    id: '/admin/assignments/',
    path: '/admin/assignments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentLearnCourseIdRoute =
  DashboardStudentLearnCourseIdRouteImport.update({
    id: '/student/learn/$courseId',
    path: '/student/learn/$courseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffStudentsStudentIdRoute =
  DashboardStaffStudentsStudentIdRouteImport.update({
    id: '/staff/students/$studentId',
    path: '/staff/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudentsStudentIdRoute =
  DashboardAdminStudentsStudentIdRouteImport.update({
    id: '/admin/students/$studentId',
    path: '/admin/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminExamsCreateRoute =
  DashboardAdminExamsCreateRouteImport.update({
    id: '/admin/exams/create',
    path: '/admin/exams/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminExamsExamIdRoute =
  DashboardAdminExamsExamIdRouteImport.update({
    id: '/admin/exams/$examId',
    path: '/admin/exams/$examId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCoursesCreateRoute =
  DashboardAdminCoursesCreateRouteImport.update({
    id: '/admin/courses/create',
    path: '/admin/courses/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCoursesCourseIdRoute =
  DashboardAdminCoursesCourseIdRouteImport.update({
    id: '/admin/courses/$courseId',
    path: '/admin/courses/$courseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentExamsExamIdAttemptRoute =
  DashboardStudentExamsExamIdAttemptRouteImport.update({
    id: '/student/exams/$examId/attempt',
    path: '/student/exams/$examId/attempt',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/student/my-learning': typeof DashboardStudentMyLearningRoute
  '/dashboard/student/study-logs': typeof DashboardStudentStudyLogsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/courses/$courseId': typeof DashboardAdminCoursesCourseIdRoute
  '/dashboard/admin/courses/create': typeof DashboardAdminCoursesCreateRoute
  '/dashboard/admin/exams/$examId': typeof DashboardAdminExamsExamIdRoute
  '/dashboard/admin/exams/create': typeof DashboardAdminExamsCreateRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/student/learn/$courseId': typeof DashboardStudentLearnCourseIdRoute
  '/dashboard/admin/assignments/': typeof DashboardAdminAssignmentsIndexRoute
  '/dashboard/admin/attendance/': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches/': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/courses/': typeof DashboardAdminCoursesIndexRoute
  '/dashboard/admin/exams/': typeof DashboardAdminExamsIndexRoute
  '/dashboard/admin/fees/': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents/': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students/': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs/': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/courses/': typeof DashboardStaffCoursesIndexRoute
  '/dashboard/staff/students/': typeof DashboardStaffStudentsIndexRoute
  '/dashboard/student/assignments/': typeof DashboardStudentAssignmentsIndexRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/exams/': typeof DashboardStudentExamsIndexRoute
  '/dashboard/student/exams/$examId/attempt': typeof DashboardStudentExamsExamIdAttemptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/student/my-learning': typeof DashboardStudentMyLearningRoute
  '/dashboard/student/study-logs': typeof DashboardStudentStudyLogsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent': typeof DashboardParentIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/courses/$courseId': typeof DashboardAdminCoursesCourseIdRoute
  '/dashboard/admin/courses/create': typeof DashboardAdminCoursesCreateRoute
  '/dashboard/admin/exams/$examId': typeof DashboardAdminExamsExamIdRoute
  '/dashboard/admin/exams/create': typeof DashboardAdminExamsCreateRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/student/learn/$courseId': typeof DashboardStudentLearnCourseIdRoute
  '/dashboard/admin/assignments': typeof DashboardAdminAssignmentsIndexRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesIndexRoute
  '/dashboard/admin/exams': typeof DashboardAdminExamsIndexRoute
  '/dashboard/admin/fees': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/courses': typeof DashboardStaffCoursesIndexRoute
  '/dashboard/staff/students': typeof DashboardStaffStudentsIndexRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsIndexRoute
  '/dashboard/student/courses': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/exams': typeof DashboardStudentExamsIndexRoute
  '/dashboard/student/exams/$examId/attempt': typeof DashboardStudentExamsExamIdAttemptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/student/my-learning': typeof DashboardStudentMyLearningRoute
  '/dashboard/student/study-logs': typeof DashboardStudentStudyLogsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/courses/$courseId': typeof DashboardAdminCoursesCourseIdRoute
  '/dashboard/admin/courses/create': typeof DashboardAdminCoursesCreateRoute
  '/dashboard/admin/exams/$examId': typeof DashboardAdminExamsExamIdRoute
  '/dashboard/admin/exams/create': typeof DashboardAdminExamsCreateRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/student/learn/$courseId': typeof DashboardStudentLearnCourseIdRoute
  '/dashboard/admin/assignments/': typeof DashboardAdminAssignmentsIndexRoute
  '/dashboard/admin/attendance/': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches/': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/courses/': typeof DashboardAdminCoursesIndexRoute
  '/dashboard/admin/exams/': typeof DashboardAdminExamsIndexRoute
  '/dashboard/admin/fees/': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents/': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students/': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs/': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/courses/': typeof DashboardStaffCoursesIndexRoute
  '/dashboard/staff/students/': typeof DashboardStaffStudentsIndexRoute
  '/dashboard/student/assignments/': typeof DashboardStudentAssignmentsIndexRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/student/exams/': typeof DashboardStudentExamsIndexRoute
  '/dashboard/student/exams/$examId/attempt': typeof DashboardStudentExamsExamIdAttemptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard/'
    | '/dashboard/student/my-learning'
    | '/dashboard/student/study-logs'
    | '/dashboard/admin/'
    | '/dashboard/analytics/'
    | '/dashboard/parent/'
    | '/dashboard/staff/'
    | '/dashboard/student/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/courses/$courseId'
    | '/dashboard/admin/courses/create'
    | '/dashboard/admin/exams/$examId'
    | '/dashboard/admin/exams/create'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/student/learn/$courseId'
    | '/dashboard/admin/assignments/'
    | '/dashboard/admin/attendance/'
    | '/dashboard/admin/batches/'
    | '/dashboard/admin/courses/'
    | '/dashboard/admin/exams/'
    | '/dashboard/admin/fees/'
    | '/dashboard/admin/parents/'
    | '/dashboard/admin/schedule/'
    | '/dashboard/admin/staff/'
    | '/dashboard/admin/students/'
    | '/dashboard/admin/study-logs/'
    | '/dashboard/staff/courses/'
    | '/dashboard/staff/students/'
    | '/dashboard/student/assignments/'
    | '/dashboard/student/courses/'
    | '/dashboard/student/exams/'
    | '/dashboard/student/exams/$examId/attempt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard'
    | '/dashboard/student/my-learning'
    | '/dashboard/student/study-logs'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/parent'
    | '/dashboard/staff'
    | '/dashboard/student'
    | '/dashboard/super-admin'
    | '/dashboard/admin/courses/$courseId'
    | '/dashboard/admin/courses/create'
    | '/dashboard/admin/exams/$examId'
    | '/dashboard/admin/exams/create'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/student/learn/$courseId'
    | '/dashboard/admin/assignments'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/batches'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/exams'
    | '/dashboard/admin/fees'
    | '/dashboard/admin/parents'
    | '/dashboard/admin/schedule'
    | '/dashboard/admin/staff'
    | '/dashboard/admin/students'
    | '/dashboard/admin/study-logs'
    | '/dashboard/staff/courses'
    | '/dashboard/staff/students'
    | '/dashboard/student/assignments'
    | '/dashboard/student/courses'
    | '/dashboard/student/exams'
    | '/dashboard/student/exams/$examId/attempt'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard/'
    | '/dashboard/student/my-learning'
    | '/dashboard/student/study-logs'
    | '/dashboard/admin/'
    | '/dashboard/analytics/'
    | '/dashboard/parent/'
    | '/dashboard/staff/'
    | '/dashboard/student/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/courses/$courseId'
    | '/dashboard/admin/courses/create'
    | '/dashboard/admin/exams/$examId'
    | '/dashboard/admin/exams/create'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/student/learn/$courseId'
    | '/dashboard/admin/assignments/'
    | '/dashboard/admin/attendance/'
    | '/dashboard/admin/batches/'
    | '/dashboard/admin/courses/'
    | '/dashboard/admin/exams/'
    | '/dashboard/admin/fees/'
    | '/dashboard/admin/parents/'
    | '/dashboard/admin/schedule/'
    | '/dashboard/admin/staff/'
    | '/dashboard/admin/students/'
    | '/dashboard/admin/study-logs/'
    | '/dashboard/staff/courses/'
    | '/dashboard/staff/students/'
    | '/dashboard/student/assignments/'
    | '/dashboard/student/courses/'
    | '/dashboard/student/exams/'
    | '/dashboard/student/exams/$examId/attempt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterInstituteRoute: typeof AuthRegisterInstituteRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-institute': {
      id: '/auth/register-institute'
      path: '/auth/register-institute'
      fullPath: '/auth/register-institute'
      preLoaderRoute: typeof AuthRegisterInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/super-admin/': {
      id: '/dashboard/super-admin/'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin/'
      preLoaderRoute: typeof DashboardSuperAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent/': {
      id: '/dashboard/parent/'
      path: '/parent'
      fullPath: '/dashboard/parent/'
      preLoaderRoute: typeof DashboardParentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/study-logs': {
      id: '/dashboard/student/study-logs'
      path: '/student/study-logs'
      fullPath: '/dashboard/student/study-logs'
      preLoaderRoute: typeof DashboardStudentStudyLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/my-learning': {
      id: '/dashboard/student/my-learning'
      path: '/student/my-learning'
      fullPath: '/dashboard/student/my-learning'
      preLoaderRoute: typeof DashboardStudentMyLearningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/exams/': {
      id: '/dashboard/student/exams/'
      path: '/student/exams'
      fullPath: '/dashboard/student/exams/'
      preLoaderRoute: typeof DashboardStudentExamsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/courses/': {
      id: '/dashboard/student/courses/'
      path: '/student/courses'
      fullPath: '/dashboard/student/courses/'
      preLoaderRoute: typeof DashboardStudentCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/assignments/': {
      id: '/dashboard/student/assignments/'
      path: '/student/assignments'
      fullPath: '/dashboard/student/assignments/'
      preLoaderRoute: typeof DashboardStudentAssignmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/students/': {
      id: '/dashboard/staff/students/'
      path: '/staff/students'
      fullPath: '/dashboard/staff/students/'
      preLoaderRoute: typeof DashboardStaffStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/courses/': {
      id: '/dashboard/staff/courses/'
      path: '/staff/courses'
      fullPath: '/dashboard/staff/courses/'
      preLoaderRoute: typeof DashboardStaffCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/study-logs/': {
      id: '/dashboard/admin/study-logs/'
      path: '/admin/study-logs'
      fullPath: '/dashboard/admin/study-logs/'
      preLoaderRoute: typeof DashboardAdminStudyLogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/students/': {
      id: '/dashboard/admin/students/'
      path: '/admin/students'
      fullPath: '/dashboard/admin/students/'
      preLoaderRoute: typeof DashboardAdminStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/staff/': {
      id: '/dashboard/admin/staff/'
      path: '/admin/staff'
      fullPath: '/dashboard/admin/staff/'
      preLoaderRoute: typeof DashboardAdminStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/schedule/': {
      id: '/dashboard/admin/schedule/'
      path: '/admin/schedule'
      fullPath: '/dashboard/admin/schedule/'
      preLoaderRoute: typeof DashboardAdminScheduleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/parents/': {
      id: '/dashboard/admin/parents/'
      path: '/admin/parents'
      fullPath: '/dashboard/admin/parents/'
      preLoaderRoute: typeof DashboardAdminParentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/fees/': {
      id: '/dashboard/admin/fees/'
      path: '/admin/fees'
      fullPath: '/dashboard/admin/fees/'
      preLoaderRoute: typeof DashboardAdminFeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/exams/': {
      id: '/dashboard/admin/exams/'
      path: '/admin/exams'
      fullPath: '/dashboard/admin/exams/'
      preLoaderRoute: typeof DashboardAdminExamsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/courses/': {
      id: '/dashboard/admin/courses/'
      path: '/admin/courses'
      fullPath: '/dashboard/admin/courses/'
      preLoaderRoute: typeof DashboardAdminCoursesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/batches/': {
      id: '/dashboard/admin/batches/'
      path: '/admin/batches'
      fullPath: '/dashboard/admin/batches/'
      preLoaderRoute: typeof DashboardAdminBatchesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/attendance/': {
      id: '/dashboard/admin/attendance/'
      path: '/admin/attendance'
      fullPath: '/dashboard/admin/attendance/'
      preLoaderRoute: typeof DashboardAdminAttendanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/assignments/': {
      id: '/dashboard/admin/assignments/'
      path: '/admin/assignments'
      fullPath: '/dashboard/admin/assignments/'
      preLoaderRoute: typeof DashboardAdminAssignmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/learn/$courseId': {
      id: '/dashboard/student/learn/$courseId'
      path: '/student/learn/$courseId'
      fullPath: '/dashboard/student/learn/$courseId'
      preLoaderRoute: typeof DashboardStudentLearnCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/students/$studentId': {
      id: '/dashboard/staff/students/$studentId'
      path: '/staff/students/$studentId'
      fullPath: '/dashboard/staff/students/$studentId'
      preLoaderRoute: typeof DashboardStaffStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/students/$studentId': {
      id: '/dashboard/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/dashboard/admin/students/$studentId'
      preLoaderRoute: typeof DashboardAdminStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/exams/create': {
      id: '/dashboard/admin/exams/create'
      path: '/admin/exams/create'
      fullPath: '/dashboard/admin/exams/create'
      preLoaderRoute: typeof DashboardAdminExamsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/exams/$examId': {
      id: '/dashboard/admin/exams/$examId'
      path: '/admin/exams/$examId'
      fullPath: '/dashboard/admin/exams/$examId'
      preLoaderRoute: typeof DashboardAdminExamsExamIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/courses/create': {
      id: '/dashboard/admin/courses/create'
      path: '/admin/courses/create'
      fullPath: '/dashboard/admin/courses/create'
      preLoaderRoute: typeof DashboardAdminCoursesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/courses/$courseId': {
      id: '/dashboard/admin/courses/$courseId'
      path: '/admin/courses/$courseId'
      fullPath: '/dashboard/admin/courses/$courseId'
      preLoaderRoute: typeof DashboardAdminCoursesCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/exams/$examId/attempt': {
      id: '/dashboard/student/exams/$examId/attempt'
      path: '/student/exams/$examId/attempt'
      fullPath: '/dashboard/student/exams/$examId/attempt'
      preLoaderRoute: typeof DashboardStudentExamsExamIdAttemptRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStudentMyLearningRoute: typeof DashboardStudentMyLearningRoute
  DashboardStudentStudyLogsRoute: typeof DashboardStudentStudyLogsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardParentIndexRoute: typeof DashboardParentIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardSuperAdminIndexRoute: typeof DashboardSuperAdminIndexRoute
  DashboardAdminCoursesCourseIdRoute: typeof DashboardAdminCoursesCourseIdRoute
  DashboardAdminCoursesCreateRoute: typeof DashboardAdminCoursesCreateRoute
  DashboardAdminExamsExamIdRoute: typeof DashboardAdminExamsExamIdRoute
  DashboardAdminExamsCreateRoute: typeof DashboardAdminExamsCreateRoute
  DashboardAdminStudentsStudentIdRoute: typeof DashboardAdminStudentsStudentIdRoute
  DashboardStaffStudentsStudentIdRoute: typeof DashboardStaffStudentsStudentIdRoute
  DashboardStudentLearnCourseIdRoute: typeof DashboardStudentLearnCourseIdRoute
  DashboardAdminAssignmentsIndexRoute: typeof DashboardAdminAssignmentsIndexRoute
  DashboardAdminAttendanceIndexRoute: typeof DashboardAdminAttendanceIndexRoute
  DashboardAdminBatchesIndexRoute: typeof DashboardAdminBatchesIndexRoute
  DashboardAdminCoursesIndexRoute: typeof DashboardAdminCoursesIndexRoute
  DashboardAdminExamsIndexRoute: typeof DashboardAdminExamsIndexRoute
  DashboardAdminFeesIndexRoute: typeof DashboardAdminFeesIndexRoute
  DashboardAdminParentsIndexRoute: typeof DashboardAdminParentsIndexRoute
  DashboardAdminScheduleIndexRoute: typeof DashboardAdminScheduleIndexRoute
  DashboardAdminStaffIndexRoute: typeof DashboardAdminStaffIndexRoute
  DashboardAdminStudentsIndexRoute: typeof DashboardAdminStudentsIndexRoute
  DashboardAdminStudyLogsIndexRoute: typeof DashboardAdminStudyLogsIndexRoute
  DashboardStaffCoursesIndexRoute: typeof DashboardStaffCoursesIndexRoute
  DashboardStaffStudentsIndexRoute: typeof DashboardStaffStudentsIndexRoute
  DashboardStudentAssignmentsIndexRoute: typeof DashboardStudentAssignmentsIndexRoute
  DashboardStudentCoursesIndexRoute: typeof DashboardStudentCoursesIndexRoute
  DashboardStudentExamsIndexRoute: typeof DashboardStudentExamsIndexRoute
  DashboardStudentExamsExamIdAttemptRoute: typeof DashboardStudentExamsExamIdAttemptRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStudentMyLearningRoute: DashboardStudentMyLearningRoute,
  DashboardStudentStudyLogsRoute: DashboardStudentStudyLogsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardParentIndexRoute: DashboardParentIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardSuperAdminIndexRoute: DashboardSuperAdminIndexRoute,
  DashboardAdminCoursesCourseIdRoute: DashboardAdminCoursesCourseIdRoute,
  DashboardAdminCoursesCreateRoute: DashboardAdminCoursesCreateRoute,
  DashboardAdminExamsExamIdRoute: DashboardAdminExamsExamIdRoute,
  DashboardAdminExamsCreateRoute: DashboardAdminExamsCreateRoute,
  DashboardAdminStudentsStudentIdRoute: DashboardAdminStudentsStudentIdRoute,
  DashboardStaffStudentsStudentIdRoute: DashboardStaffStudentsStudentIdRoute,
  DashboardStudentLearnCourseIdRoute: DashboardStudentLearnCourseIdRoute,
  DashboardAdminAssignmentsIndexRoute: DashboardAdminAssignmentsIndexRoute,
  DashboardAdminAttendanceIndexRoute: DashboardAdminAttendanceIndexRoute,
  DashboardAdminBatchesIndexRoute: DashboardAdminBatchesIndexRoute,
  DashboardAdminCoursesIndexRoute: DashboardAdminCoursesIndexRoute,
  DashboardAdminExamsIndexRoute: DashboardAdminExamsIndexRoute,
  DashboardAdminFeesIndexRoute: DashboardAdminFeesIndexRoute,
  DashboardAdminParentsIndexRoute: DashboardAdminParentsIndexRoute,
  DashboardAdminScheduleIndexRoute: DashboardAdminScheduleIndexRoute,
  DashboardAdminStaffIndexRoute: DashboardAdminStaffIndexRoute,
  DashboardAdminStudentsIndexRoute: DashboardAdminStudentsIndexRoute,
  DashboardAdminStudyLogsIndexRoute: DashboardAdminStudyLogsIndexRoute,
  DashboardStaffCoursesIndexRoute: DashboardStaffCoursesIndexRoute,
  DashboardStaffStudentsIndexRoute: DashboardStaffStudentsIndexRoute,
  DashboardStudentAssignmentsIndexRoute: DashboardStudentAssignmentsIndexRoute,
  DashboardStudentCoursesIndexRoute: DashboardStudentCoursesIndexRoute,
  DashboardStudentExamsIndexRoute: DashboardStudentExamsIndexRoute,
  DashboardStudentExamsExamIdAttemptRoute:
    DashboardStudentExamsExamIdAttemptRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterInstituteRoute: AuthRegisterInstituteRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
